apiVersion: v1
kind: Service
metadata:
  name: maria-svc-headless
  labels:
    app: maria-svc-headless
spec:
  ports:
    - name: http
      port: 80
  clusterIP: None
  selector:
    app: mariadb-sts