apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-headless
  labels:
    app: mongo-svc-headless
spec:
  ports:
    - name: http
      port: 80
  clusterIP: None
  selector:
    app: mongodb-sts