apiVersion: v1
kind: Pod
metadata:
  name: dind-pod
  namespace: devops-tools
spec:
  containers:
    - name: dind-container
      image: docker:stable-dind
      securityContext:
        privileged: true  # 권한 상승 너무 위험해~
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock  # 호스트의 Docker 소켓 마운트
  volumes:
    - name: docker-socket
      persistentVolumeClaim:
        claimName: jenkins-pv-claim

