apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - name: 'j8080'
      port: 8080
      targetPort: 8080
      nodePort: 32000
    - name: 'j50000'
      port: 50000
      targetPort: 50000

