apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:                       ## 표2 스테이트풀셋 사양
  serviceName: redis       ## 특징② 연결할 서비스의 이름 설정
  replicas: 1               # 파드 기동 개수
  selector:
    matchLabels:
      app: redis-sts
  template:                 ## 표3 파드의 템플릿
    metadata:
      labels:
        app: redis-sts
    spec:
      containers:           
      - name: redis
        image: redis:7.2.4
        env:
        - name: REDIS_PASSWORD
          value: "3322"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
          - containerPort: 6379
            name: client
          - containerPort: 16379
            name: gossip
        volumeMounts:       ## 특징③ 컨테이너상의 마운트 경로 설정 
        - name: redis-pvc
          mountPath: /data
          subPath: data     ## 초기화 시 빈 디렉터리가 필요
        livenessProbe:      ## MySQL 기동 확인 
          exec:
            command: ["sh","-c","redis-cli -a {{ .Values.app.env.REDIS_PASSWORD }} ping"]
          initialDelaySeconds: 60
          timeoutSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 2Gi
