## 디플로이먼트
apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-deploy
spec:
  replicas: 1
  selector:           # deployment - pod 대응용
    matchLabels:
      app: host-app
  template:           # 여기서부터 파드 템플릿
    metadata:
      labels:
        app: host-app      # 파드의 라벨
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: hostcont
          image: shinyenggwak/moija-front
          imagePullPolicy: Always
          ports:
            - containerPort: 3000


