## 디플로이먼트
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
spec:
  replicas: 1
  selector:           # deployment - pod 대응용
    matchLabels:
      app: user-app
  template:           # 여기서부터 파드 템플릿
    metadata:
      labels:
        app: user-app      # 파드의 라벨
    spec:
      containers:
      - name: usercont
        image: shinyenggwak/moija-auth:cloud-0.4.1
        imagePullPolicy: Always
        ports:
         - containerPort: 8088
        env:
            - name: DATASOURCE_URL ## 컨테이너 환경 변수명
              valueFrom:
                configMapKeyRef:
                  name: env-config ## 컨피그맵명
                  key: datasource_url ## 키 항목
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: redis_url

            - name: MOIJA_POST_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: post_url
            - name: MOIJA_MY_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: my_url


